#!/bin/sh
set -e -u
cp src/tests.py "$AUTOPKGTEST_TMP/"
cd "$AUTOPKGTEST_TMP/"
py3versions -s \
| tr ' ' '\n' \
| xargs -I {} env PYTHONWARNINGS=d {} \
  ./tests.py --verbose 2>&1

# vim:ts=4 sw=4 et
